

services:
  db:
    container_name: postgres-login
    build: ./postgres
    restart: unless-stopped
    # image: postgres:17
    # restart: always
    ports:
      - "7000:5432"
    env_file:
      - p.env
    volumes:
      - ./pg-data:/var/lib/postgresql/data
  
  redis:
    image: redis
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly yes
