"""first migration

Revision ID: 0477f0365103
Revises: 
Create Date: 2025-04-08 15:26:23.447177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0477f0365103'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), server_default=sa.text('uuid_generate_v4()'), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.Column('update_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_uuid'), 'customers', ['uuid'], unique=False)
    op.create_table('desk_customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('desk_uuid', sa.String(), nullable=True),
    sa.Column('customer_uuid', sa.String(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.Column('update_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('desks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), server_default=sa.text('uuid_generate_v4()'), nullable=True),
    sa.Column('desk_name', sa.String(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.Column('update_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desks_uuid'), 'desks', ['uuid'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), server_default=sa.text('uuid_generate_v4()'), nullable=True),
    sa.Column('permission_name', sa.String(), nullable=True),
    sa.Column('permission_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.Column('update_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_uuid'), 'permissions', ['uuid'], unique=False)
    op.create_table('role_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_uuid', sa.String(), nullable=True),
    sa.Column('permission_uuid', sa.String(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.Column('update_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=True),
    sa.Column('role_uuid', sa.String(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.Column('update_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), server_default=sa.text('uuid_generate_v4()'), nullable=True),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.Column('update_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_uuid'), 'roles', ['uuid'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), server_default=sa.text('uuid_generate_v4()'), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('_password', postgresql.BYTEA(), nullable=True),
    sa.Column('email',sa.String(), nullable=False),
    sa.Column('info', postgresql.JSONB(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.Column('update_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_uuid'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('role_user')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_permissions_uuid'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_desks_uuid'), table_name='desks')
    op.drop_table('desks')
    op.drop_table('desk_customer')
    op.drop_index(op.f('ix_customers_uuid'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
