"""first migration

Revision ID: 1db0963d563b
Revises: 
Create Date: 2025-06-23 11:04:15.568663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1db0963d563b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), server_default=sa.text('uuid_generate_v4()'), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.Column('update_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_customers_uuid'), 'customers', ['uuid'], unique=False)
    op.create_table('desk_customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('desk_uuid', sa.String(), nullable=True),
    sa.Column('customer_uuid', sa.String(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.Column('update_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('desks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), server_default=sa.text('uuid_generate_v4()'), nullable=True),
    sa.Column('desk_name', sa.String(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.Column('update_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desks_uuid'), 'desks', ['uuid'], unique=False)
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), server_default=sa.text('uuid_generate_v4()'), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('min_stock', sa.Integer(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.Column('update_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_uuid'), 'ingredients', ['uuid'], unique=False)
    op.create_table('menu_item_ingredients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), server_default=sa.text('uuid_generate_v4()'), nullable=True),
    sa.Column('menu_item_uuid', sa.String(), nullable=True),
    sa.Column('ingredient_uuid', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.Column('update_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_item_ingredients_uuid'), 'menu_item_ingredients', ['uuid'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), server_default=sa.text('uuid_generate_v4()'), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.Column('update_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_items_uuid'), 'menu_items', ['uuid'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), server_default=sa.text('uuid_generate_v4()'), nullable=True),
    sa.Column('order_uuid', sa.String(), nullable=True),
    sa.Column('item_uuid', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.Column('update_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_uuid'), 'order_items', ['uuid'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), server_default=sa.text('uuid_generate_v4()'), nullable=True),
    sa.Column('customer_uuid', sa.String(), nullable=True),
    sa.Column('desk_uuid', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.Column('update_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_uuid'), 'orders', ['uuid'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), server_default=sa.text('uuid_generate_v4()'), nullable=True),
    sa.Column('order_uuid', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('amount_paid', sa.Integer(), nullable=True),
    sa.Column('payment_note', sa.String(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.Column('update_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_uuid'), 'payments', ['uuid'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), server_default=sa.text('uuid_generate_v4()'), nullable=True),
    sa.Column('permission_name', sa.String(), nullable=True),
    sa.Column('permission_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.Column('update_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_uuid'), 'permissions', ['uuid'], unique=False)
    op.create_table('role_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_uuid', sa.String(), nullable=True),
    sa.Column('permission_uuid', sa.String(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.Column('update_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=True),
    sa.Column('role_uuid', sa.String(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.Column('update_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), server_default=sa.text('uuid_generate_v4()'), nullable=True),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.Column('update_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_uuid'), 'roles', ['uuid'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), server_default=sa.text('uuid_generate_v4()'), nullable=True),
    sa.Column('ingredient_uuid', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('stock_type', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.Column('update_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_uuid'), 'stocks', ['uuid'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), server_default=sa.text('uuid_generate_v4()'), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('_password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('info', postgresql.JSONB(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.Column('update_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stocks_uuid'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_roles_uuid'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('role_user')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_permissions_uuid'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_payments_uuid'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_orders_uuid'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_order_items_uuid'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_menu_items_uuid'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_menu_item_ingredients_uuid'), table_name='menu_item_ingredients')
    op.drop_table('menu_item_ingredients')
    op.drop_index(op.f('ix_ingredients_uuid'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_desks_uuid'), table_name='desks')
    op.drop_table('desks')
    op.drop_table('desk_customer')
    op.drop_index(op.f('ix_customers_uuid'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
