"""first migration

Revision ID: e76ad9cd0742
Revises: 
Create Date: 2024-10-25 15:06:49.946867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e76ad9cd0742'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(), server_default=sa.text('uuid_generate_v4()'), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('_password', postgresql.BYTEA(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('desk_number', sa.Integer(), nullable=True),
    sa.Column('user_status', sa.Integer(), nullable=True, comment='0:員工用 1:內用'),
    sa.Column('active', sa.Boolean(), nullable=True, comment='0:沒登入用 1:登入用'),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('creat_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.Column('update_dt', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
